# Site settings
title: Rails Assessment Project Booktopia
header-img: img/home-bg.png
email: enoch2k2@hotmail.com
copyright_name: Enoch2k2
description: > # this means to ignore newlines until "baseurl:"
  Rails Final Assessment
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Enoch2k2
learn_profile: Enoch2k2
email_username: enoch2k2@hotmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
